// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectPRN232_HRM.Models;

#nullable disable

namespace ProjectPRN232_HRM.Migrations
{
    [DbContext(typeof(ProjectPrn232HrmanagementContext))]
    partial class ProjectPrn232HrmanagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("CheckIn")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("CheckOut")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Normal");

                    b.Property<decimal?>("WorkHours")
                        .HasColumnType("decimal(4, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Attendan__3214EC077941A050");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Benefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DocumentUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ProbationPeriod")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProbationSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly?>("SignedDate")
                        .HasColumnType("date");

                    b.Property<string>("SigningPlace")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TermsAndConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingHours")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Contract__3214EC07D13357EB");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex(new[] { "ContractNumber" }, "UQ__Contract__C51D43DAC7FAEC34")
                        .IsUnique();

                    b.ToTable("Contract", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Departme__3214EC07E1D39C43");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("ParentDepartmentId");

                    b.HasIndex(new[] { "DepartmentCode" }, "UQ__Departme__6EA8896D2AEA9098")
                        .IsUnique();

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.EmergencyContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Relationship")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Emergenc__3214EC079A5E9DFB");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmergencyContact", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly>("JoinDate")
                        .HasColumnType("date");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("NationalId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NationalID");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Employee__3214EC07DAF4A017");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Employee_Email");

                    b.HasIndex("EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("UQ__Employee__1F642548318A6A1A");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("PositionId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.EmployeeDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Employee__3214EC07AA36C12A");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("EmployeeDocument", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.EmployeeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ChangeDate")
                        .HasColumnType("date");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Employee__3214EC0786FE778B");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeHistory", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.EmployeeSkill", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Certification")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("CertifiedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProficiencyLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmployeeId", "SkillId")
                        .HasName("PK__Employee__172A4609FB330E1D");

                    b.HasIndex("SkillId");

                    b.ToTable("EmployeeSkill", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.EmployeeTraining", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingProgramId")
                        .HasColumnType("int");

                    b.Property<string>("CertificateUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CompletionStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("Result")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeId", "TrainingProgramId")
                        .HasName("PK__Employee__BE28D8B49CBA82C8");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("EmployeeTraining", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id")
                        .HasName("PK__LeaveReq__3214EC071E003BB3");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveRequest", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxDaysPerYear")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__LeaveTyp__3214EC07494E307E");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("LeaveType", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.PerformanceReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<string>("AreasForImprovement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BehaviorScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("CompetencyScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DevelopmentPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("OverallScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("PerformanceScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("ReviewPeriod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Strengths")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Performa__3214EC0798519EAF");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("PerformanceReview", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("SalaryFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(10m);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Position__3214EC0734B88FC7");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex(new[] { "PositionCode" }, "UQ__Position__83745B02F53B89C5")
                        .IsUnique();

                    b.ToTable("Position", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.RewardDiscipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DecisionNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__RewardDi__3214EC0733A3EF5E");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EmployeeId");

                    b.ToTable("RewardDiscipline", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Allowance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Bonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("Deduction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Insurance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal?>("NetSalary")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(24, 2)")
                        .HasComputedColumnSql("(((((([BasicSalary]+[Allowance])+[Bonus])+[OvertimePay])-[Deduction])-[Tax])-[Insurance])", true);

                    b.Property<decimal?>("OvertimePay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<decimal?>("Tax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Salary__3214EC07EA4CDAAE");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Salary", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SkillCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Skill__3214EC07E30DAA9C");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex(new[] { "SkillCode" }, "UQ__Skill__59F57E0930860F63")
                        .IsUnique();

                    b.ToTable("Skill", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.TrainingProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Training__3214EC07F6563DAC");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex(new[] { "ProgramCode" }, "UQ__Training__7658A987CCDBC5FF")
                        .IsUnique();

                    b.ToTable("TrainingProgram", (string)null);
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Attendance", b =>
                {
                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "ApprovedByNavigation")
                        .WithMany("AttendanceApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK__Attendanc__Appro__5FB337D6");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "Employee")
                        .WithMany("AttendanceEmployees")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__Attendanc__Emplo__5EBF139D");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Contract", b =>
                {
                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "CreatedByNavigation")
                        .WithMany("ContractCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Contract__Create__71D1E811");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "Employee")
                        .WithMany("ContractEmployees")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__Contract__Employ__70DDC3D8");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "ModifiedByNavigation")
                        .WithMany("ContractModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Contract__Modifi__72C60C4A");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Employee");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Department", b =>
                {
                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "CreatedByNavigation")
                        .WithMany("DepartmentCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Department_CreatedBy_Employee_Id");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "ModifiedByNavigation")
                        .WithMany("DepartmentModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK_Department_ModifiedBy_Employee_Id");

                    b.HasOne("ProjectPRN232_HRM.Models.Department", "ParentDepartment")
                        .WithMany("InverseParentDepartment")
                        .HasForeignKey("ParentDepartmentId")
                        .HasConstraintName("FK__Departmen__Paren__4AB81AF0");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.EmergencyContact", b =>
                {
                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "Employee")
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__Emergency__Emplo__1CBC4616");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Employee", b =>
                {
                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "CreatedByNavigation")
                        .WithMany("InverseCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Employee__Create__5441852A");

                    b.HasOne("ProjectPRN232_HRM.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK__Employee__Depart__5165187F");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "Manager")
                        .WithMany("InverseManager")
                        .HasForeignKey("ManagerId")
                        .HasConstraintName("FK__Employee__Manage__534D60F1");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "ModifiedByNavigation")
                        .WithMany("InverseModifiedByNavigation")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Employee__Modifi__5535A963");

                    b.HasOne("ProjectPRN232_HRM.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .HasConstraintName("FK__Employee__Positi__52593CB8");

                    b.HasOne("ProjectPRN232_HRM.Models.ApplicationUser", "User")
                        .WithOne("Employee")
                        .HasForeignKey("ProjectPRN232_HRM.Models.Employee", "UserId")
                        .HasConstraintName("FK_Employee_ApplicationUser_UserId");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Department");

                    b.Navigation("Manager");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.EmployeeDocument", b =>
                {
                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "CreatedByNavigation")
                        .WithMany("EmployeeDocumentCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__EmployeeD__Creat__2180FB33");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "Employee")
                        .WithMany("EmployeeDocumentEmployees")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__EmployeeD__Emplo__208CD6FA");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "ModifiedByNavigation")
                        .WithMany("EmployeeDocumentModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__EmployeeD__Modif__22751F6C");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Employee");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.EmployeeHistory", b =>
                {
                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "ChangedByNavigation")
                        .WithMany("EmployeeHistoryChangedByNavigations")
                        .HasForeignKey("ChangedBy")
                        .HasConstraintName("FK__EmployeeH__Chang__04E4BC85");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "Employee")
                        .WithMany("EmployeeHistoryEmployees")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__EmployeeH__Emplo__03F0984C");

                    b.Navigation("ChangedByNavigation");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.EmployeeSkill", b =>
                {
                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "Employee")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__EmployeeS__Emplo__0D7A0286");

                    b.HasOne("ProjectPRN232_HRM.Models.Skill", "Skill")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK__EmployeeS__Skill__0E6E26BF");

                    b.Navigation("Employee");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.EmployeeTraining", b =>
                {
                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "Employee")
                        .WithMany("EmployeeTrainings")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__EmployeeT__Emplo__17036CC0");

                    b.HasOne("ProjectPRN232_HRM.Models.TrainingProgram", "TrainingProgram")
                        .WithMany("EmployeeTrainings")
                        .HasForeignKey("TrainingProgramId")
                        .IsRequired()
                        .HasConstraintName("FK__EmployeeT__Train__17F790F9");

                    b.Navigation("Employee");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.LeaveRequest", b =>
                {
                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "ApprovedByNavigation")
                        .WithMany("LeaveRequestApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK__LeaveRequ__Appro__6C190EBB");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "Employee")
                        .WithMany("LeaveRequestEmployees")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__LeaveRequ__Emplo__6A30C649");

                    b.HasOne("ProjectPRN232_HRM.Models.LeaveType", "LeaveType")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeaveTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__LeaveRequ__Leave__6B24EA82");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.LeaveType", b =>
                {
                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "CreatedByNavigation")
                        .WithMany("LeaveTypeCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__LeaveType__Creat__6477ECF3");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "ModifiedByNavigation")
                        .WithMany("LeaveTypeModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__LeaveType__Modif__656C112C");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.PerformanceReview", b =>
                {
                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "ApprovedByNavigation")
                        .WithMany("PerformanceReviewApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK__Performan__Appro__29221CFB");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "Employee")
                        .WithMany("PerformanceReviewEmployees")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__Performan__Emplo__2739D489");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "Reviewer")
                        .WithMany("PerformanceReviewReviewers")
                        .HasForeignKey("ReviewerId")
                        .IsRequired()
                        .HasConstraintName("FK__Performan__Revie__282DF8C2");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Employee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Position", b =>
                {
                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "CreatedByNavigation")
                        .WithMany("PositionCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Position_CreatedBy_Employee_Id");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "ModifiedByNavigation")
                        .WithMany("PositionModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK_Position_ModifiedBy_Employee_Id");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.RewardDiscipline", b =>
                {
                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "ApprovedByNavigation")
                        .WithMany("RewardDisciplineApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK__RewardDis__Appro__2FCF1A8A");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "CreatedByNavigation")
                        .WithMany("RewardDisciplineCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__RewardDis__Creat__2EDAF651");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "Employee")
                        .WithMany("RewardDisciplineEmployees")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__RewardDis__Emplo__2DE6D218");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Salary", b =>
                {
                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "ApprovedByNavigation")
                        .WithMany("SalaryApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK__Salary__Approved__00200768");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "CreatedByNavigation")
                        .WithMany("SalaryCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Salary__CreatedB__7E37BEF6");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "Employee")
                        .WithMany("SalaryEmployees")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__Salary__Employee__7D439ABD");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "ModifiedByNavigation")
                        .WithMany("SalaryModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Salary__Modified__7F2BE32F");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Employee");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Skill", b =>
                {
                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "CreatedByNavigation")
                        .WithMany("SkillCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Skill__CreatedBy__09A971A2");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "ModifiedByNavigation")
                        .WithMany("SkillModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__Skill__ModifiedB__0A9D95DB");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.TrainingProgram", b =>
                {
                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "CreatedByNavigation")
                        .WithMany("TrainingProgramCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__TrainingP__Creat__1332DBDC");

                    b.HasOne("ProjectPRN232_HRM.Models.Employee", "ModifiedByNavigation")
                        .WithMany("TrainingProgramModifiedByNavigations")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK__TrainingP__Modif__14270015");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.ApplicationUser", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("InverseParentDepartment");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Employee", b =>
                {
                    b.Navigation("AttendanceApprovedByNavigations");

                    b.Navigation("AttendanceEmployees");

                    b.Navigation("ContractCreatedByNavigations");

                    b.Navigation("ContractEmployees");

                    b.Navigation("ContractModifiedByNavigations");

                    b.Navigation("DepartmentCreatedByNavigations");

                    b.Navigation("DepartmentModifiedByNavigations");

                    b.Navigation("EmergencyContacts");

                    b.Navigation("EmployeeDocumentCreatedByNavigations");

                    b.Navigation("EmployeeDocumentEmployees");

                    b.Navigation("EmployeeDocumentModifiedByNavigations");

                    b.Navigation("EmployeeHistoryChangedByNavigations");

                    b.Navigation("EmployeeHistoryEmployees");

                    b.Navigation("EmployeeSkills");

                    b.Navigation("EmployeeTrainings");

                    b.Navigation("InverseCreatedByNavigation");

                    b.Navigation("InverseManager");

                    b.Navigation("InverseModifiedByNavigation");

                    b.Navigation("LeaveRequestApprovedByNavigations");

                    b.Navigation("LeaveRequestEmployees");

                    b.Navigation("LeaveTypeCreatedByNavigations");

                    b.Navigation("LeaveTypeModifiedByNavigations");

                    b.Navigation("PerformanceReviewApprovedByNavigations");

                    b.Navigation("PerformanceReviewEmployees");

                    b.Navigation("PerformanceReviewReviewers");

                    b.Navigation("PositionCreatedByNavigations");

                    b.Navigation("PositionModifiedByNavigations");

                    b.Navigation("RewardDisciplineApprovedByNavigations");

                    b.Navigation("RewardDisciplineCreatedByNavigations");

                    b.Navigation("RewardDisciplineEmployees");

                    b.Navigation("SalaryApprovedByNavigations");

                    b.Navigation("SalaryCreatedByNavigations");

                    b.Navigation("SalaryEmployees");

                    b.Navigation("SalaryModifiedByNavigations");

                    b.Navigation("SkillCreatedByNavigations");

                    b.Navigation("SkillModifiedByNavigations");

                    b.Navigation("TrainingProgramCreatedByNavigations");

                    b.Navigation("TrainingProgramModifiedByNavigations");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.LeaveType", b =>
                {
                    b.Navigation("LeaveRequests");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.Skill", b =>
                {
                    b.Navigation("EmployeeSkills");
                });

            modelBuilder.Entity("ProjectPRN232_HRM.Models.TrainingProgram", b =>
                {
                    b.Navigation("EmployeeTrainings");
                });
#pragma warning restore 612, 618
        }
    }
}
